apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: petstore
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000